name: Testing Symfony
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup NodeJs  
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install -q --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install -D

      - name: Run PHPStan
        run: composer run-script phpstan

      - name: Run Coding Standard
        run: composer run-script ccs

      - name: Check formatting with Prettier
        run: npm run format:check

      - name: Run Tests
        run: composer run-script test
